FROM rhel7.5:1.0

ENV HOMEDIR /home/appuser

RUN groupadd appuser && useradd -g appuser appuser -m && /bin/echo 'appuser:123456'|chpasswd

WORKDIR $HOMEDIR

ADD tomcat-8.tar.gz .
ADD jre8.tar.gz .

RUN chown -R appuser:appuser ${HOMEDIR}
USER appuser

ENV CATALINA_HOME ${HOMEDIR}/tomcat-8
ADD iammonitor.war $CATALINA_HOME/webapps/iammonitor.war 

ENV LANG=zh_CN.UTF-8
ENV JAVA_HOME=${HOMEDIR}/jre8
ENV PATH=${CATALINA_HOME}/bin:${JAVA_HOME}/bin:$PATH
ENV CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar

ENTRYPOINT ${CATALINA_HOME}/bin/startup.sh \
&& tail -f ${CATALINA_HOME}/logs/catalina.out
